### ISSUE TITLE
The requested package dkushnikov/yii2-yandex-metrika could not be found in any version

### ISSUE THREAD

**Issue by abrgitlab** [dkushnikov/yii2-yandex-metrika#3]
Subj

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package dkushnikov/yii2-yandex-metrika could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by dkushnikov** [comment]
Looks like you have stability version conflict. I've add release version (v1.0). Try to specify it in you composer.json.
